export const fonts = [
  {
    font: { family: 'Abril Fatface', style: 'normal', weight: 'normal' },
    name: 'Abril Fatface Regular',
    active: false,
  },
  { font: { family: 'Alegreya', style: 'normal', weight: 'bold' }, name: 'Alegreya Bold', active: false },
  { font: { family: 'Alegreya', style: 'italic', weight: 'bold' }, name: 'Alegreya Bold Italic', active: false },
  { font: { family: 'Alegreya', style: 'italic', weight: 'normal' }, name: 'Alegreya Italic', active: false },
  { font: { family: 'Alegreya', style: 'normal', weight: 'normal' }, name: 'Alegreya Regular', active: false },
  { font: { family: 'Alegreya SC', style: 'normal', weight: 'bold' }, name: 'Alegreya SC Bold', active: false },
  { font: { family: 'Alegreya SC', style: 'italic', weight: 'normal' }, name: 'Alegreya SC Italic', active: false },
  { font: { family: 'Alegreya SC', style: 'normal', weight: 'normal' }, name: 'Alegreya SC Regular', active: false },
  { font: { family: 'Alegreya Sans', style: 'italic', weight: 'normal' }, name: 'Alegreya Sans Italic', active: false },
  { font: { family: 'Amarante', style: 'normal', weight: 'normal' }, name: 'Amarante Regular', active: false },
  { font: { family: 'Amatic SC', style: 'normal', weight: 'bold' }, name: 'Amatic SC Bold', active: false },
  { font: { family: 'Arial', style: 'normal', weight: 'bold' }, name: 'Arial Bold', active: false },
  { font: { family: 'Arial', style: 'italic', weight: 'bold' }, name: 'Arial Bold Italic', active: false },
  { font: { family: 'Arial', style: 'italic', weight: 'normal' }, name: 'Arial Italic', active: false },
  { font: { family: 'Arial', style: 'normal', weight: 'normal' }, name: 'Arial Regular', active: true },
  {
    font: { family: 'Arial Unicode MS', style: 'normal', weight: 'bold' },
    name: 'Arial Unicode MS Bold',
    active: false,
  },
  {
    font: { family: 'Arial Unicode MS', style: 'normal', weight: 'normal' },
    name: 'Arial Unicode MS Regular',
    active: false,
  },
  { font: { family: 'Atomic Age', style: 'normal', weight: 'normal' }, name: 'Atomic Age Regular', active: false },
  { font: { family: 'Audiowide', style: 'normal', weight: 'normal' }, name: 'Audiowide Regular', active: false },
  {
    font: { family: 'Avenir Next LT Pro', style: 'normal', weight: 'bold' },
    name: 'Avenir Next LT Pro Bold',
    active: false,
  },
  {
    font: { family: 'Avenir Next LT Pro', style: 'italic', weight: 'bold' },
    name: 'Avenir Next LT Pro Bold Italic',
    active: false,
  },
  {
    font: { family: 'Avenir Next LT Pro Demi', style: 'italic', weight: 'normal' },
    name: 'Avenir Next LT Pro Demi Italic',
    active: false,
  },
  {
    font: { family: 'Avenir Next LT Pro', style: 'italic', weight: 'normal' },
    name: 'Avenir Next LT Pro Italic',
    active: false,
  },
  {
    font: { family: 'Avenir Next LT Pro Light', style: 'normal', weight: 'normal' },
    name: 'Avenir Next LT Pro Light',
    active: false,
  },
  {
    font: { family: 'Avenir Next LT Pro Light', style: 'italic', weight: 'normal' },
    name: 'Avenir Next LT Pro Light Italic',
    active: false,
  },
  {
    font: { family: 'Avenir Next LT Pro', style: 'normal', weight: 'normal' },
    name: 'Avenir Next LT Pro Regular',
    active: false,
  },
  {
    font: { family: 'AvenirNext LT Pro Light', style: 'italic', weight: 'normal' },
    name: 'AvenirNext LT Pro Light Italic',
    active: false,
  },
  {
    font: { family: 'AvenirNext LT Pro Light', style: 'normal', weight: 'normal' },
    name: 'AvenirNext LT Pro Light Regula, active: falser',
  },
  {
    font: { family: 'AvenirNext LT Pro Medium', style: 'normal', weight: 'bold' },
    name: 'AvenirNext LT Pro Medium Bold',
    active: false,
  },
  {
    font: { family: 'AvenirNext LT Pro Medium', style: 'italic', weight: 'bold' },
    name: 'AvenirNext LT Pro Medium Bold Italic',
    active: false,
  },
  {
    font: { family: 'AvenirNext LT Pro Regular', style: 'normal', weight: 'bold' },
    name: 'AvenirNext LT Pro Regular Bold',
    active: false,
  },
  {
    font: { family: 'AvenirNext LT Pro Regular', style: 'italic', weight: 'bold' },
    name: 'AvenirNext LT Pro Regular Bold Italic',
    active: false,
  },
  {
    font: { family: 'AvenirNext LT Pro Regular', style: 'italic', weight: 'normal' },
    name: 'AvenirNext LT Pro Regular Italic',
    active: false,
  },
  {
    font: { family: 'AvenirNext LT Pro Regular', style: 'normal', weight: 'normal' },
    name: 'AvenirNext LT Pro Regular Regula, active: falser',
  },
  { font: { family: 'Belleza', style: 'normal', weight: 'normal' }, name: 'Belleza Regular', active: false },
  {
    font: { family: 'Black Ops One', style: 'normal', weight: 'normal' },
    name: 'Black Ops One Regular',
    active: false,
  },
  { font: { family: 'Cabin Sketch', style: 'normal', weight: 'bold' }, name: 'Cabin Sketch Bold', active: false },
  { font: { family: 'Cabin Sketch', style: 'normal', weight: 'normal' }, name: 'Cabin Sketch Regular', active: false },
  { font: { family: 'Coming Soon', style: 'normal', weight: 'normal' }, name: 'Coming Soon Regular', active: false },
  {
    font: { family: 'Homemade Apple', style: 'normal', weight: 'normal' },
    name: 'Homemade Apple Regular',
    active: false,
  },
  {
    font: { family: 'IM FELL DW Pica PRO', style: 'italic', weight: 'normal' },
    name: 'IM FELL DW Pica PRO Italic',
    active: false,
  },
  {
    font: { family: 'IM FELL DW Pica PRO', style: 'normal', weight: 'normal' },
    name: 'IM FELL DW Pica PRO Regular',
    active: false,
  },
  { font: { family: 'Josefin Sans', style: 'normal', weight: 'normal' }, name: 'Josefin Sans Regular', active: false },
  { font: { family: 'Josefin Slab', style: 'normal', weight: 'bold' }, name: 'Josefin Slab Bold', active: false },
  {
    font: { family: 'Josefin Slab', style: 'italic', weight: 'bold' },
    name: 'Josefin Slab Bold Italic',
    active: false,
  },
  { font: { family: 'Josefin Slab', style: 'italic', weight: 'normal' }, name: 'Josefin Slab Italic', active: false },
  {
    font: { family: 'Josefin Slab Light', style: 'italic', weight: 'normal' },
    name: 'Josefin Slab Light Italic',
    active: false,
  },
  { font: { family: 'Josefin Slab', style: 'normal', weight: 'normal' }, name: 'Josefin Slab Regular', active: false },
  {
    font: { family: 'Josefin Slab Thin', style: 'italic', weight: 'normal' },
    name: 'Josefin Slab Thin Italic',
    active: false,
  },
  {
    font: { family: 'Just Another Hand', style: 'normal', weight: 'normal' },
    name: 'Just Another Hand Regular',
    active: false,
  },
  { font: { family: 'Kranky', style: 'normal', weight: 'normal' }, name: 'Kranky Regular', active: false },
  { font: { family: 'Life Savers', style: 'normal', weight: 'bold' }, name: 'Life Savers Bold', active: false },
  {
    font: { family: 'Loved by the King', style: 'normal', weight: 'normal' },
    name: 'Loved by the King Regular',
    active: false,
  },
  { font: { family: 'Merriweather', style: 'normal', weight: 'bold' }, name: 'Merriweather Bold', active: false },
  {
    font: { family: 'Merriweather', style: 'italic', weight: 'bold' },
    name: 'Merriweather Bold Italic',
    active: false,
  },
  { font: { family: 'Merriweather', style: 'italic', weight: 'normal' }, name: 'Merriweather Italic', active: false },
  { font: { family: 'Merriweather', style: 'normal', weight: 'normal' }, name: 'Merriweather Regular', active: false },
  { font: { family: 'Montserrat', style: 'normal', weight: 'bold' }, name: 'Montserrat Bold', active: false },
  { font: { family: 'Montserrat', style: 'italic', weight: 'normal' }, name: 'Montserrat Italic', active: false },
  {
    font: { family: 'Montserrat Medium', style: 'italic', weight: 'normal' },
    name: 'Montserrat Medium Italic',
    active: false,
  },
  { font: { family: 'Montserrat', style: 'normal', weight: 'normal' }, name: 'Montserrat Regular', active: false },
  { font: { family: 'Noto Sans', style: 'normal', weight: 'bold' }, name: 'Noto Sans Bold', active: false },
  { font: { family: 'Noto Sans', style: 'italic', weight: 'bold' }, name: 'Noto Sans Bold Italic', active: false },
  { font: { family: 'Noto Sans', style: 'italic', weight: 'normal' }, name: 'Noto Sans Italic', active: false },
  { font: { family: 'Noto Sans', style: 'normal', weight: 'normal' }, name: 'Noto Sans Regular', active: false },
  { font: { family: 'Noto Serif', style: 'normal', weight: 'bold' }, name: 'Noto Serif Bold', active: false },
  { font: { family: 'Noto Serif', style: 'italic', weight: 'bold' }, name: 'Noto Serif Bold Italic', active: false },
  { font: { family: 'Noto Serif', style: 'italic', weight: 'normal' }, name: 'Noto Serif Italic', active: false },
  { font: { family: 'Noto Serif', style: 'normal', weight: 'normal' }, name: 'Noto Serif Regular', active: false },
  { font: { family: 'Old Standard TT', style: 'normal', weight: 'bold' }, name: 'Old Standard TT Bold', active: false },
  {
    font: { family: 'Old Standard TT', style: 'italic', weight: 'normal' },
    name: 'Old Standard TT Italic',
    active: false,
  },
  {
    font: { family: 'Old Standard TT', style: 'normal', weight: 'normal' },
    name: 'Old Standard TT Regular',
    active: false,
  },
  { font: { family: 'Orbitron', style: 'normal', weight: 'bold' }, name: 'Orbitron Bold', active: false },
  { font: { family: 'Orbitron', style: 'normal', weight: 'normal' }, name: 'Orbitron Regular', active: false },
  { font: { family: 'Oregano', style: 'italic', weight: 'normal' }, name: 'Oregano Italic', active: false },
  { font: { family: 'Oregano', style: 'normal', weight: 'normal' }, name: 'Oregano Regular', active: false },
  { font: { family: 'Oswald', style: 'normal', weight: 'bold' }, name: 'Oswald Bold', active: false },
  { font: { family: 'Oswald', style: 'normal', weight: 'normal' }, name: 'Oswald Regular', active: false },
  { font: { family: 'Pacifico', style: 'normal', weight: 'normal' }, name: 'Pacifico Regular', active: false },
  {
    font: { family: 'Palatino Linotype', style: 'normal', weight: 'normal' },
    name: 'Palatino Linotype Regular',
    active: false,
  },
  {
    font: { family: 'Playfair Display Black', style: 'normal', weight: 'normal' },
    name: 'Playfair Display Black',
    active: false,
  },
  {
    font: { family: 'Playfair Display Black', style: 'normal', weight: 'normal' },
    name: 'Playfair Display Black Regula, active: falser',
  },
  {
    font: { family: 'Playfair Display', style: 'normal', weight: 'bold' },
    name: 'Playfair Display Bold',
    active: false,
  },
  {
    font: { family: 'Playfair Display', style: 'italic', weight: 'bold' },
    name: 'Playfair Display Bold Italic',
    active: false,
  },
  {
    font: { family: 'Playfair Display', style: 'italic', weight: 'normal' },
    name: 'Playfair Display Italic',
    active: false,
  },
  {
    font: { family: 'Playfair Display', style: 'normal', weight: 'normal' },
    name: 'Playfair Display Regular',
    active: false,
  },
  {
    font: { family: 'Playfair Display SC', style: 'normal', weight: 'bold' },
    name: 'Playfair Display SC Bold',
    active: false,
  },
  {
    font: { family: 'Playfair Display SC', style: 'normal', weight: 'normal' },
    name: 'Playfair Display SC Regular',
    active: false,
  },
  { font: { family: 'Redressed', style: 'normal', weight: 'normal' }, name: 'Redressed Regular', active: false },
  { font: { family: 'Risque', style: 'normal', weight: 'normal' }, name: 'Risque Regular', active: false },
  {
    font: { family: 'Roboto Condensed', style: 'italic', weight: 'normal' },
    name: 'Roboto Condensed Italic',
    active: false,
  },
  {
    font: { family: 'Roboto Condensed Light', style: 'italic', weight: 'normal' },
    name: 'Roboto Condensed Light Italic',
    active: false,
  },
  { font: { family: 'Rye', style: 'normal', weight: 'normal' }, name: 'Rye Regular', active: false },
  {
    font: { family: 'Special Elite', style: 'normal', weight: 'normal' },
    name: 'Special Elite Regular',
    active: false,
  },
  { font: { family: 'Syncopate', style: 'normal', weight: 'bold' }, name: 'Syncopate Bold', active: false },
  { font: { family: 'Syncopate', style: 'normal', weight: 'normal' }, name: 'Syncopate Regular', active: false },
  { font: { family: 'Tangerine', style: 'normal', weight: 'normal' }, name: 'Tangerine Regular', active: false },
  { font: { family: 'Ubuntu', style: 'normal', weight: 'bold' }, name: 'Ubuntu Bold', active: false },
  { font: { family: 'Ubuntu', style: 'italic', weight: 'bold' }, name: 'Ubuntu Bold Italic', active: false },
  {
    font: { family: 'Ubuntu Condensed', style: 'normal', weight: 'normal' },
    name: 'Ubuntu Condensed Regular',
    active: false,
  },
  { font: { family: 'Ubuntu', style: 'italic', weight: 'normal' }, name: 'Ubuntu Italic', active: false },
  { font: { family: 'Ubuntu Light', style: 'normal', weight: 'normal' }, name: 'Ubuntu Light', active: false },
  { font: { family: 'Ubuntu Light', style: 'normal', weight: 'bold' }, name: 'Ubuntu Light Bold', active: false },
  {
    font: { family: 'Ubuntu Light', style: 'italic', weight: 'bold' },
    name: 'Ubuntu Light Bold Italic',
    active: false,
  },
  { font: { family: 'Ubuntu Light', style: 'italic', weight: 'normal' }, name: 'Ubuntu Light Italic', active: false },
  { font: { family: 'Ubuntu Light', style: 'normal', weight: 'normal' }, name: 'Ubuntu Light Regular', active: false },
  { font: { family: 'Ubuntu Medium', style: 'italic', weight: 'normal' }, name: 'Ubuntu Medium Italic', active: false },
  { font: { family: 'Ubuntu Mono', style: 'normal', weight: 'bold' }, name: 'Ubuntu Mono Bold', active: false },
  { font: { family: 'Ubuntu Mono', style: 'italic', weight: 'bold' }, name: 'Ubuntu Mono Bold Italic', active: false },
  { font: { family: 'Ubuntu Mono', style: 'italic', weight: 'normal' }, name: 'Ubuntu Mono Italic', active: false },
  { font: { family: 'Ubuntu Mono', style: 'normal', weight: 'normal' }, name: 'Ubuntu Mono Regular', active: false },
  { font: { family: 'Ubuntu', style: 'normal', weight: 'normal' }, name: 'Ubuntu Regular', active: false },
  { font: { family: 'UnifrakturCook', style: 'normal', weight: 'bold' }, name: 'UnifrakturCook Bold', active: false },
  { font: { family: 'Vast Shadow', style: 'normal', weight: 'normal' }, name: 'Vast Shadow Regular', active: false },
  {
    font: { family: 'Walter Turncoat', style: 'normal', weight: 'normal' },
    name: 'Walter Turncoat Regular',
    active: false,
  },
];
